version: "3.9"
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:${REDIS_PORT}"
        networks:
            - api_net
        command: 
            - redis-server
        volumes: 
            - redis_data:/data
    postgres:
        image: postgres:10.5
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - DATABASE_HOST=api 
        ports:
            - '5432:${POSTGRES_PORT}'
        networks:
            - api_net
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        depends_on: 
            - postgres
        ports: 
            - "5050:5050"
        networks: 
            - api_net
    web:
        build: "./web/"
        ports: 
            - "80:80"
        depends_on:
            - api          
    api: 
        build: ./api/
        ports: 
            - "8080:${API_PORT}"
        links: 
            - redis
            - postgres
        depends_on: 
            - postgres
        networks:
            - api_net
networks:
    api_net:
        driver: bridge

volumes: 
    postgres_data:
    redis_data: