version: "3.9"
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - api_net
        volumes: 
            - redis_data:/data
    postgres:
        image: postgres:10.5
        restart: always
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=test
            - DATABASE_HOST=api 
        ports:
            - '5432:5432'
        networks:
            - api_net
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        depends_on: 
            - postgres
        ports: 
            - "5050:5050"
        networks: 
            - api_net
    web:
        build: "./web/"
        ports: 
            - "80:80"
        depends_on:
            - api          
    api: 
        build: ./api/
        ports: 
            - "8080:8080"
        links: 
            - redis
            - postgres
        depends_on: 
            - postgres
        networks:
            - api_net
networks:
    api_net:
        driver: bridge

volumes: 
    postgres_data:
    redis_data: